FROM jetty:9-jre8
MAINTAINER pi-Geosolutions "jp@pigeosolutions.fr"

ARG GEOSERVER_VERSION=2.20
ARG GEOSERVER_MINOR_VERSION=2
# ARG WEBAPP_PATH "ROOT"
ARG WEBAPP_PATH="geoserver"

USER root
RUN mkdir /tmp/geoserver /mnt/geoserver_datadir /mnt/geoserver_geodata /mnt/geoserver_tiles && \
    chown -R jetty:jetty /tmp/geoserver /mnt/geoserver_datadir /mnt/geoserver_geodata /mnt/geoserver_tiles

# Install geoserver
#COPY --chown=jetty:jetty geoserver-2.20.2-war.zip /tmp/geoserver.zip
#RUN unzip -o /tmp/geoserver.zip -d /tmp/geoserver && \
#    unzip -o /tmp/geoserver/geoserver.war -d $JETTY_BASE/webapps/${WEBAPP_PATH} && \
#    rm -rf $JETTY_BASE/webapps/${WEBAPP_PATH}/WEB-INF/lib/marlin-*.jar && \
#    rm -r /tmp/*
RUN curl -L https://sourceforge.net/projects/geoserver/files/GeoServer/${GEOSERVER_VERSION}.${GEOSERVER_MINOR_VERSION}/geoserver-${GEOSERVER_VERSION}.${GEOSERVER_MINOR_VERSION}-war.zip/download > /tmp/geoserver.zip && \
    unzip -o /tmp/geoserver.zip -d /tmp/geoserver && \
    unzip -o /tmp/geoserver/geoserver.war -d $JETTY_BASE/webapps/${WEBAPP_PATH} && \
    rm -rf $JETTY_BASE/webapps/${WEBAPP_PATH}/WEB-INF/lib/marlin-*.jar && \
    rm -r /tmp/*

# Install Marlin
RUN wget https://github.com/bourgesl/marlin-renderer/releases/download/v0.9.0/marlin-0.9.0-Unsafe.jar -O $JETTY_BASE/webapps/${WEBAPP_PATH}/WEB-INF/lib/marlin.jar && \
    wget https://github.com/bourgesl/marlin-renderer/releases/download/v0.9.0/marlin-0.9.0-Unsafe-sun-java2d.jar -O $JETTY_BASE/webapps/${WEBAPP_PATH}/WEB-INF/lib/marlin-sun-java2d.jar

VOLUME [ "/mnt/geoserver_datadir", "/mnt/geoserver_geodata", "/mnt/geoserver_tiles", "/tmp" ]

# space-separate list of plugins to install
ARG PLUGINS_EXT="cas css control-flow vectortiles"
ARG PLUGINS_COMMUNITY=""

# Install plugins if some listed
# Official plugins
RUN for plugin in $PLUGINS_EXT; do \
    echo "https://build.geoserver.org/geoserver/${GEOSERVER_VERSION}.x/ext-latest/geoserver-${GEOSERVER_VERSION}-SNAPSHOT-${plugin}-plugin.zip > /tmp/${plugin}-plugin.zip" &&\
    curl -L https://build.geoserver.org/geoserver/${GEOSERVER_VERSION}.x/ext-latest/geoserver-${GEOSERVER_VERSION}-SNAPSHOT-${plugin}-plugin.zip > /tmp/${plugin}-plugin.zip && \
    unzip -o /tmp/${plugin}-plugin.zip -d $JETTY_BASE/webapps/${WEBAPP_PATH}/WEB-INF/lib/ &&\
    rm /tmp/* ; \
  done

# Community plugins
RUN for plugin in $PLUGINS_COMMUNITY; do \
    echo "https://build.geoserver.org/geoserver/${GEOSERVER_VERSION}.x/community-latest/geoserver-${GEOSERVER_VERSION}-SNAPSHOT-${plugin}-plugin.zip > /tmp/${plugin}-plugin.zip" &&\
    curl -L https://build.geoserver.org/geoserver/${GEOSERVER_VERSION}.x/community-latest/geoserver-${GEOSERVER_VERSION}-SNAPSHOT-${plugin}-plugin.zip > /tmp/${plugin}-plugin.zip && \
    unzip -o /tmp/${plugin}-plugin.zip -d $JETTY_BASE/webapps/${WEBAPP_PATH}/WEB-INF/lib/ &&\
    rm /tmp/* ; \
  done

ENV JAVA_OPTS "-Xms256M \
 -Xbootclasspath/a:$JETTY_BASE/webapps/${WEBAPP_PATH}/WEB-INF/lib/marlin.jar \
 -Xbootclasspath/p:$JETTY_BASE/webapps/${WEBAPP_PATH}/WEB-INF/lib/marlin-sun-java2d.jar \
 -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine \
 -DGEOSERVER_DATA_DIR=/mnt/geoserver_datadir \
 -DGEOWEBCACHE_CACHE_DIR=/mnt/geoserver_tiles \
 -DENABLE_JSONP=true \
 -Dorg.geotools.coverage.jaiext.enabled=true \
 -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 \
 -XX:SoftRefLRUPolicyMSPerMB=36000 \
 -XX:+UnlockExperimentalVMOptions \
 -XX:+UseCGroupMemoryLimitForHeap"

# Copy CORS-enabled web.xml in Jetty (used or not, depends on env var, see entrypoint)
COPY web-cors-jetty.xml $JETTY_BASE/webapps/${WEBAPP_PATH}/WEB-INF/web-cors.xml

COPY --chown=jetty:jetty entrypoint.sh /entrypoint.sh
RUN chmod u+x /entrypoint.sh &&\
    chown -R jetty:jetty $JETTY_BASE/webapps/${WEBAPP_PATH}


USER jetty

# Make an env var out of the ARG variable, to make it available to the entrypoint
ENV WEBAPP_PATH=${WEBAPP_PATH}
ENV ENABLE_CORS="false"

ENTRYPOINT ["/entrypoint.sh"]

CMD ["java","-jar","/usr/local/jetty/start.jar"]
